paths:
  raw_dataset_dir: data\pnoa\raw
  processed_dataset_dir: data\pnoa\processed


dataset:
  name: pnoa_lidar
  tile_size: 120
  overlap: 10

path:
  dataset_path: 'Aragon' 
  exp_name: 'exp_pnoa_ptv3'

preprocess:
  channels:
    - xyz
    - rgb
    - intensity
    - return_num
    - num_returns


class_mapping:
  Suelo:
    original_ids: [2]
    
  Vegetacion_Baja:
    original_ids: [3]
    
  Vegetacion_Med_Alta:
    original_ids: [4, 5]
    
  Edificios:
    original_ids: [6]
    
  Agua:
    original_ids: [9] 
    
  Cables:
    original_ids: [14]
    
  Torres:
    original_ids: [15]
    
  Puentes:
    original_ids: [16, 17]
    
  Vehiculos:
    original_ids: [63, 64]
    
  Paneles:
    original_ids: [67]
    
  Aerogeneradores:
    original_ids: [68]
    

model:
  num_classes: 11
  dropout: 0.5

training:
  batch_size: 16
  epochs: 200
  num_workers: 4
  device: cuda
  seed: 1

validation:
  batch_size: 16
  metrics: [accuracy, mIoU, F1]

inference:
  batch_size: 16
